<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import AdminLayout from '@/components/admin/AdminLayout.vue'
import UserService, { type UserDTO } from '@/services/UserService'
import BranchService, { type BranchDTO } from '@/services/BranchService'
import { useToast } from '@/composables/useToast'
import { useConfirm } from '@/composables/useConfirm'
import { useUserStore } from '@/stores/user'
import UsersList from './UsersList.vue'
import UserEditor from './UserEditor.vue'
import { accountTypes, type UserForm } from './types'
const users = ref<UserDTO[]>([]); const branches = ref<BranchDTO[]>([]); const loading = ref(true); const saving = ref(false); const open = ref(false); const editingId = ref(''); const { success, error } = useToast(); const { confirm } = useConfirm(); const userStore = useUserStore()
const form = reactive<UserForm>({ email:'', password:'', name:'', phone:'', accountType:'branch_admin', branches:[], allBranches:false })
const branchOptions = computed(() => branches.value.map((branch) => ({ value:branch._id, label:branch.name }))); const labels = { customer:'Cliente', branch_admin:'Admin. sucursal', admin:'Admin' }
function reset() { Object.assign(form, { email:'', password:'', name:'', phone:'', accountType:'branch_admin', branches:[], allBranches:false }); editingId.value = '' }
async function load() { loading.value = true; try { const [usersData, branchesData] = await Promise.all([UserService.getAll(), BranchService.getAll()]); users.value = usersData.data; branches.value = branchesData.data } catch { error('No se pudieron cargar los usuarios') } finally { loading.value = false } }
function create() { reset(); open.value = true }; function edit(user: UserDTO) { Object.assign(form, { email:user.email, password:'', name:user.name || '', phone:'', accountType:user.accountType, branches:user.branches?.map((branch) => branch._id) || [], allBranches:user.allBranches || false }); editingId.value = user._id; open.value = true }; function close() { open.value = false; setTimeout(reset, 150) }
async function save() { try { saving.value = true; const payload: Record<string, unknown> = { email:form.email, name:form.name || undefined, accountType:form.accountType, branches:form.branches, allBranches:form.allBranches }; if (form.password) payload.password = form.password; if (editingId.value) await UserService.update(editingId.value, payload); else await UserService.create(payload); success(editingId.value ? 'Usuario actualizado' : 'Usuario creado'); close(); await load() } catch { error('No se pudo guardar el usuario') } finally { saving.value = false } }
async function remove(user: UserDTO) { if (userStore.id === user._id) return error('No puedes eliminarte a ti mismo'); if (!await confirm({ title:'¿Eliminar usuario?', message:`${user.name || user.email} perderá acceso a Boloncity. Esta acción no se puede deshacer.`, confirmText:'Sí, eliminar usuario', cancelText:'Conservar usuario', type:'danger' })) return; try { await UserService.remove(user._id); users.value = users.value.filter((item) => item._id !== user._id); success('Usuario eliminado') } catch { error('No se pudo eliminar el usuario') } }
onMounted(load)
</script>
<template><AdminLayout><main class="users"><section class="hero panel"><div><p>Equipo y permisos</p><h1>Usuarios</h1><span>Administra quién puede acceder a Boloncity y a qué sucursales.</span></div><button type="button" @click="create"><i class="fa-solid fa-user-plus" /> Nuevo usuario</button></section><section class="stats"><article class="panel"><span>Usuarios</span><strong>{{ users.length }}</strong></article><article class="panel"><span>Administradores</span><strong>{{ users.filter((user) => user.accountType !== 'customer').length }}</strong></article><article class="panel"><span>Con acceso global</span><strong>{{ users.filter((user) => user.allBranches).length }}</strong></article></section><UsersList :users="users" :loading="loading" :labels="labels" @create="create" @edit="edit" @remove="remove" /><UserEditor :open="open" :editing="Boolean(editingId)" :saving="saving" :form="form" :account-options="accountTypes" :branch-options="branchOptions" @close="close" @submit="save" /></main></AdminLayout></template>
<style scoped lang="scss">.users { display:flex; flex-direction:column; gap:1rem; padding:clamp(.75rem,2vw,1.5rem); }.hero { align-items:flex-start; background:linear-gradient(135deg,#235931,#173e22); color:#fff; display:flex; flex-direction:column; gap:1rem; justify-content:space-between; padding:1.25rem; }.hero p { color:#efd537; font-size:.72rem; font-weight:900; letter-spacing:.12em; text-transform:uppercase; }.hero h1 { font-size:clamp(1.7rem,4vw,2.5rem); margin:.35rem 0; }.hero span { color:rgba(255,255,255,.76); }.hero button { align-items:center; background:#efd537; border:0; border-radius:999px; color:#152019; display:inline-flex; font-weight:900; gap:.45rem; justify-content:center; min-height:42px; padding:.7rem .95rem; width:100%; }.stats { display:flex; flex-wrap:wrap; gap:.55rem; }.stats article { display:flex; flex:1 1 calc((100% - 1.1rem) / 3); flex-direction:column; min-width:0; padding:.75rem; }.stats span { color:var(--admin-muted); font-size:.58rem; font-weight:900; letter-spacing:.05em; overflow-wrap:anywhere; text-transform:uppercase; }.stats strong { color:#235931; font-size:1.55rem; margin-top:.25rem; } @media (min-width:641px) { .hero { align-items:center; flex-direction:row; }.hero button { width:auto; }.stats { gap:.8rem; }.stats article { flex-basis:160px; padding:1rem; }.stats span { font-size:.7rem; }.stats strong { font-size:2rem; } }</style>
