<script setup lang="ts">
import type { UserDTO } from '@/services/UserService'
defineProps<{ users: UserDTO[]; loading: boolean; labels: Record<string, string> }>()
const emit = defineEmits<{ create: []; edit: [user: UserDTO]; remove: [user: UserDTO] }>()
</script>
<template>
  <section class="users-list panel">
    <header><div><p>Equipo y acceso</p><h2>Usuarios registrados</h2></div><button type="button" @click="emit('create')"><i class="fa-solid fa-user-plus" /> Nuevo usuario</button></header>
    <div v-if="loading" class="loading"><i class="fa-solid fa-spinner fa-spin" /><span>Cargando usuarios</span></div>
    <div v-else-if="users.length" class="list"><article v-for="user in users" :key="user._id" :class="{ 'user-card--customer': user.accountType === 'customer' }"><div class="user-summary"><div class="avatar"><i v-if="user.accountType === 'customer'" class="fa-solid fa-user" /><template v-else>{{ (user.name || user.email).slice(0, 1).toUpperCase() }}</template></div><div class="content"><div><strong>{{ user.name || user.email }}</strong><span>{{ labels[user.accountType] || user.accountType }}</span><em v-if="user.accountType === 'customer'"><i class="fa-solid fa-wand-magic-sparkles" /> Registro automático</em></div><p>{{ user.email }}</p><small><i :class="user.accountType === 'customer' ? 'fa-solid fa-cart-shopping' : 'fa-solid fa-store'" /> {{ user.accountType === 'customer' ? 'Cuenta creada desde la tienda' : user.allBranches ? 'Todas las sucursales' : user.branches?.map((branch) => branch.name).join(', ') || 'Sin sucursales asignadas' }}</small></div></div><div class="actions"><button type="button" @click="emit('edit', user)"><i class="fa-solid fa-pen" /> Editar</button><button class="danger" type="button" :aria-label="`Eliminar ${user.email}`" @click="emit('remove', user)"><i class="fa-solid fa-trash" /></button></div></article></div>
    <div v-else class="empty"><i class="fa-solid fa-users" /> Aún no hay usuarios registrados.</div>
  </section>
</template>
<style scoped lang="scss">
.users-list { padding:1rem; }.users-list header,.users-list article,.user-summary,.content > div,.actions { align-items:center; display:flex; gap:.65rem; }.users-list header { justify-content:space-between; margin-bottom:.85rem; }.users-list header > button { display:none; }.users-list header p { color:#235931; font-size:.7rem; font-weight:900; letter-spacing:.1em; text-transform:uppercase; }.users-list h2 { font-size:1.1rem; margin-top:.2rem; }.users-list button { align-items:center; background:#235931; border:0; border-radius:999px; color:#fff; display:inline-flex; font-weight:800; gap:.4rem; min-height:38px; padding:.55rem .75rem; }.list { display:flex; flex-direction:column; }.list article { border-top:1px solid var(--admin-line); flex-direction:column; padding:.85rem 0; }.user-summary { align-items:flex-start; width:100%; }.avatar { align-items:center; background:#235931; border-radius:50%; color:#fff; display:flex; flex:0 0 44px; font-size:.9rem; font-weight:900; height:44px; justify-content:center; width:44px; }.content { flex:1; min-width:0; }.content > div { align-items:flex-start; flex-wrap:wrap; }.content strong,.content p,.content small { overflow-wrap:anywhere; }.content strong { font-size:.95rem; }.content span { background:rgba(35,89,49,.1); border-radius:999px; color:#235931; font-size:.62rem; font-weight:900; padding:.25rem .4rem; text-transform:uppercase; }.content p,.content small { color:var(--admin-muted); display:block; font-size:.75rem; margin-top:.25rem; }.actions { width:100%; }.actions button:first-child { flex:1; justify-content:center; }.actions button { background:rgba(8,17,13,.07); color:var(--admin-text); }.actions .danger { background:rgba(180,35,24,.1); color:#b42318; }.loading,.empty { align-items:center; color:var(--admin-muted); display:flex; flex-direction:column; gap:.6rem; justify-content:center; min-height:210px; }.loading i { color:#235931; font-size:1.75rem; }.empty i { color:#00a523; font-size:1.5rem; } @media (min-width:641px) { .users-list header > button { display:inline-flex; }.list article { flex-direction:row; }.user-summary { width:auto; }.actions { justify-content:flex-end; width:auto; }.actions button:first-child { flex:none; } }
@media (min-width:641px) { .user-summary { flex:1 1 auto; }.actions { margin-left:auto; } }
.content em { background:rgba(239,213,55,.28); border-radius:999px; color:#706000; font-size:.6rem; font-style:normal; font-weight:900; padding:.25rem .4rem; }.user-card--customer { background:linear-gradient(90deg,rgba(239,213,55,.08),transparent); }.user-card--customer .avatar { background:#efd537; color:#5d5100; }.user-card--customer .content span { background:rgba(239,213,55,.23); color:#706000; }
</style>
