<script setup lang="ts">
import type { BranchDTO } from '@/services/BranchService'
defineProps<{ branches: BranchDTO[]; loading: boolean; pickerLoadingId: string }>()
const emit = defineEmits<{ create: []; edit: [branch: BranchDTO]; remove: [branch: BranchDTO]; picker: [branch: BranchDTO] }>()
function linked(branch: BranchDTO) { return ['active', 'imported'].includes(branch.pickerStore?.creationStatus || '') }
</script>
<template>
  <section class="branches-list panel"><header><div><p>Red operativa</p><h2>Sucursales registradas</h2></div><button type="button" @click="emit('create')"><i class="fa-solid fa-plus" /> Nueva sucursal</button></header><div v-if="loading" class="empty"><i class="fa-solid fa-spinner fa-spin" /> Cargando sucursales</div><div v-else class="list"><article v-for="branch in branches" :key="branch._id"><div class="branch-summary"><div class="avatar"><img v-if="branch.imageUrl" :src="branch.imageUrl" :alt="branch.name" /><i v-else class="fa-solid fa-store" /></div><div class="content"><div><strong>{{ branch.name }}</strong><span :class="{ off: !branch.isActive }">{{ branch.isActive ? 'Activa' : 'Inactiva' }}</span><span :class="{ pending: !linked(branch) }"><i :class="linked(branch) ? 'fa-solid fa-link' : 'fa-solid fa-link-slash'" /> {{ linked(branch) ? 'Picker vinculado' : 'Picker pendiente' }}</span></div><p><i class="fa-solid fa-location-dot" /> {{ branch.address || 'Sin dirección' }}</p><small><i class="fa-solid fa-clock" /> {{ branch.openingHours?.[0]?.opensAt || '07:00' }} - {{ branch.openingHours?.[0]?.closesAt || '13:00' }}</small></div></div><div class="actions"><button type="button" @click="emit('edit', branch)"><i class="fa-solid fa-pen" /> Editar</button><button type="button" :disabled="pickerLoadingId === branch._id" @click="emit('picker', branch)"><i :class="pickerLoadingId === branch._id ? 'fa-solid fa-spinner fa-spin' : 'fa-solid fa-plug'" /> {{ pickerLoadingId === branch._id ? 'Vinculando...' : 'Picker' }}</button><button type="button" class="danger" :aria-label="`Eliminar ${branch.name}`" @click="emit('remove', branch)"><i class="fa-solid fa-trash" /></button></div></article></div></section>
</template>
<style scoped lang="scss">
.branches-list { padding:1rem; }.branches-list header,.branches-list article,.branch-summary,.content > div,.actions { align-items:center; display:flex; gap:.65rem; }.branches-list header { justify-content:space-between; margin-bottom:.85rem; }.branches-list header > button { display:none; }.branches-list header p { color:#235931; font-size:.7rem; font-weight:900; letter-spacing:.1em; text-transform:uppercase; }.branches-list h2 { font-size:1.1rem; margin-top:.2rem; }.branches-list button { align-items:center; background:#235931; border:0; border-radius:999px; color:#fff; display:inline-flex; font-weight:800; gap:.4rem; min-height:38px; padding:.55rem .75rem; }.list { display:flex; flex-direction:column; }.list article { border-top:1px solid var(--admin-line); flex-direction:column; padding:.85rem 0; }.branch-summary { align-items:flex-start; width:100%; }.avatar { align-items:center; background:rgba(35,89,49,.1); border-radius:12px; color:#235931; display:flex; flex:0 0 46px; height:46px; justify-content:center; overflow:hidden; width:46px; }.avatar img { height:100%; object-fit:cover; width:100%; }.content { flex:1; min-width:0; }.content > div { align-items:flex-start; flex-wrap:wrap; }.content strong,.content p,.content small { overflow-wrap:anywhere; }.content strong { font-size:.95rem; }.content span { background:rgba(35,89,49,.1); border-radius:999px; color:#235931; font-size:.62rem; font-weight:900; padding:.25rem .4rem; text-transform:uppercase; }.content span.off,.content span.pending { background:rgba(180,35,24,.1); color:#b42318; }.content p,.content small { color:var(--admin-muted); display:block; font-size:.75rem; margin-top:.25rem; }.actions { flex-wrap:wrap; width:100%; }.actions button:not(.danger) { flex:1; justify-content:center; }.actions button { background:rgba(8,17,13,.07); color:var(--admin-text); }.actions .danger { background:rgba(180,35,24,.1); color:#b42318; }.empty { align-items:center; color:var(--admin-muted); display:flex; flex-direction:column; gap:.55rem; padding:2rem; text-align:center; }.empty i { color:#235931; font-size:1.5rem; } @media (min-width:641px) { .branches-list header > button { display:inline-flex; }.list article { flex-direction:row; }.branch-summary { width:auto; }.actions { justify-content:flex-end; width:auto; }.actions button:not(.danger) { flex:none; } }
</style>
