<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import AdminLayout from '@/components/admin/AdminLayout.vue'
import BranchService, { type BranchDTO } from '@/services/BranchService'
import { useConfirm } from '@/composables/useConfirm'
import { useToast } from '@/composables/useToast'
import BranchWizard from './BranchWizard.vue'
import BranchesList from './BranchesList.vue'
import BranchPickerLinkModal from './BranchPickerLinkModal.vue'
import { defaultHours, type BranchForm } from './types'
const branches = ref<BranchDTO[]>([]); const loading = ref(true); const pickerLoadingId = ref(''); const pickerOpen = ref(false); const pickerBranch = ref<BranchDTO | null>(null); const open = ref(false); const saving = ref(false); const editingId = ref(''); const { confirm } = useConfirm(); const { success, error } = useToast()
const form = reactive<BranchForm>({ name:'', city:'', address:'', phone:'', email:'', googleMapsUrl:'', payphoneStoreId:'', isActive:true, openingHours:defaultHours(), imageFile:null, imagePreview:'' })
const activeCount = computed(() => branches.value.filter((branch) => branch.isActive).length)
// Cuenta la llave del entorno que está corriendo el backend, no `creationStatus`.
const pickerLinkedCount = computed(() => branches.value.filter((branch) => branch.pickerEnv === 'production' ? branch.pickerStore?.hasProdKey : branch.pickerStore?.hasDevKey).length)
function reset() { Object.assign(form, { name:'', city:'', address:'', phone:'', email:'', googleMapsUrl:'', payphoneStoreId:'', isActive:true, openingHours:defaultHours(), imageFile:null, imagePreview:'' }); editingId.value = '' }
async function load() { loading.value = true; try { branches.value = (await BranchService.getAll()).data } catch { error('No se pudieron cargar las sucursales') } finally { loading.value = false } }
function create() { reset(); open.value = true }
function edit(branch: BranchDTO) { Object.assign(form, { name:branch.name, city:branch.city || '', address:branch.address || '', phone:branch.phone || '', email:branch.email || '', googleMapsUrl:branch.googleMapsUrl || '', payphoneStoreId:branch.payphone?.storeId || '', isActive:branch.isActive, openingHours:branch.openingHours?.map((day) => ({ ...day })) || defaultHours(), imageFile:null, imagePreview:branch.imageUrl || '' }); editingId.value = branch._id; open.value = true }
function close() { open.value = false; setTimeout(reset, 180) }
async function save() { if (!form.name.trim() || !form.city.trim() || !form.phone.trim() || !form.email.trim()) { error('Completa los datos de la sucursal antes de guardarla'); return } if (!form.address.trim()) { error('Completa la ubicación de la sucursal antes de guardarla'); return } try { saving.value = true; const payload = { ...form, payphoneStoreId: undefined, payphone: { storeId: form.payphoneStoreId.trim() }, imageFile: undefined, imagePreview: undefined, timezone:'America/Guayaquil' }; const branch = editingId.value ? (await BranchService.update(editingId.value, payload)).data : (await BranchService.create(payload)).data; if (form.imageFile) await BranchService.uploadImage(branch._id, form.imageFile); success(editingId.value ? 'Sucursal actualizada' : 'Sucursal creada'); close(); await load() } catch { error('No se pudo guardar la sucursal') } finally { saving.value = false } }
async function remove(branch: BranchDTO) { if (!await confirm({ title:'¿Quitar esta sucursal de Boloncity?', message:`${branch.name} dejará de aparecer y no podrá recibir pedidos desde Boloncity. Si tiene órdenes, se archivará aquí para conservar su historial. Su Store y sus datos en Picker Express no se eliminarán ni modificarán.`, confirmText:'Sí, quitar de Boloncity', cancelText:'Conservar sucursal', type:'danger' })) return; try { await BranchService.remove(branch._id); success('Sucursal eliminada o archivada'); await load() } catch { error('No se pudo eliminar la sucursal') } }
// Las tiendas ya existen en Picker: se vincula la sucursal a la suya, no se crea otra.
function picker(branch: BranchDTO) { pickerBranch.value = branch; pickerOpen.value = true }
function closePicker() { pickerOpen.value = false; setTimeout(() => { pickerBranch.value = null }, 180) }
async function onPickerLinked() { await load(); pickerBranch.value = branches.value.find((item) => item._id === pickerBranch.value?._id) || pickerBranch.value }
onMounted(load)
</script>

<template><AdminLayout><main class="branches"><section class="hero panel"><div><p>Operación y delivery</p><h1>Sucursales</h1><span>Gestiona locales, horarios, conexión con Picker y disponibilidad de pedidos.</span></div><button type="button" @click="create"><i class="fa-solid fa-plus" /> Nueva sucursal</button></section><section class="stats"><article class="panel"><span>Registradas</span><strong>{{ branches.length }}</strong></article><article class="panel"><span>Activas</span><strong>{{ activeCount }}</strong></article><article class="panel"><span>Picker vinculado</span><strong>{{ pickerLinkedCount }}</strong></article><article class="panel"><span>PayPhone listo</span><strong>{{ branches.filter((branch) => branch.payphone?.storeId).length }}</strong></article></section><BranchesList :branches="branches" :loading="loading" :picker-loading-id="pickerLoadingId" @create="create" @edit="edit" @remove="remove" @picker="picker" /><BranchWizard :open="open" :editing="Boolean(editingId)" :saving="saving" :form="form" @close="close" @submit="save" /><BranchPickerLinkModal :open="pickerOpen" :branch="pickerBranch" @close="closePicker" @linked="onPickerLinked" /></main></AdminLayout></template>

<style scoped lang="scss">
.branches { display:flex; flex-direction:column; gap:1rem; padding:clamp(.75rem,2vw,1.5rem); }.hero { align-items:flex-start; background:linear-gradient(135deg,#235931,#173e22); color:#fff; display:flex; flex-direction:column; gap:1rem; justify-content:space-between; padding:1.25rem; }.hero p { color:#efd537; font-size:.72rem; font-weight:900; letter-spacing:.12em; text-transform:uppercase; }.hero h1 { font-size:clamp(1.7rem,4vw,2.5rem); margin:.35rem 0; }.hero span { color:rgba(255,255,255,.76); }.hero button { align-items:center; background:#efd537; border:0; border-radius:999px; color:#152019; display:inline-flex; font-weight:900; gap:.45rem; justify-content:center; min-height:42px; padding:.7rem .95rem; width:100%; }.stats { display:flex; flex-wrap:wrap; gap:.55rem; }.stats article { display:flex; flex:1 1 calc((100% - 1.1rem) / 3); flex-direction:column; min-width:0; padding:.75rem; }.stats span { color:var(--admin-muted); font-size:.58rem; font-weight:900; letter-spacing:.05em; overflow-wrap:anywhere; text-transform:uppercase; }.stats strong { color:#235931; font-size:1.55rem; margin-top:.25rem; } @media (min-width:641px) { .hero { align-items:center; flex-direction:row; }.hero button { width:auto; }.stats { gap:.8rem; }.stats article { flex-basis:160px; padding:1rem; }.stats span { font-size:.7rem; }.stats strong { font-size:2rem; } }
</style>
