<script setup lang="ts">
import { computed } from 'vue'
import type { OrderDTO } from '@/services/OrderService'

const props = defineProps<{ audit: OrderDTO['audit'] }>()
const entries = computed(() => [...(props.audit || [])].filter((entry) => entry.action === 'note_added' || entry.details).slice(-5).reverse())
const labels: Record<string, { label: string; icon: string; tone: string }> = { note_added:{ label:'Nota', icon:'fa-note-sticky', tone:'note' }, status_change:{ label:'Estado actualizado', icon:'fa-route', tone:'status' }, payment_confirmed:{ label:'Pago confirmado', icon:'fa-credit-card', tone:'payment' } }
function formatTime(value: string) { return new Date(value).toLocaleString('es-EC', { dateStyle:'short', timeStyle:'short' }) }
</script>
<template>
  <section class="history"><header><span><i class="fa-solid fa-clock-rotate-left" /> Historial reciente</span><small>{{ entries.length }} movimiento{{ entries.length === 1 ? '' : 's' }}</small></header><div v-if="entries.length" class="history__list"><article v-for="entry in entries" :key="`${entry.action}-${entry.timestamp}`" :class="labels[entry.action]?.tone || 'status'"><span class="history__icon"><i :class="['fa-solid', labels[entry.action]?.icon || 'fa-circle-info']" /></span><div><strong>{{ labels[entry.action]?.label || 'Actualización' }}</strong><p>{{ entry.details || `${entry.fromValue || '—'} → ${entry.toValue || '—'}` }}</p><small>{{ entry.performedByEmail || 'Sistema' }} · {{ formatTime(entry.timestamp) }}</small></div></article></div><div v-else class="history__empty"><i class="fa-solid fa-comment-dots" /> Aún no hay notas ni movimientos registrados.</div></section>
</template>
<style scoped lang="scss">
.history { display:flex; flex-direction:column; gap:.75rem; }.history header { align-items:center; display:flex; justify-content:space-between; }.history header span { color:#235931; font-size:.7rem; font-weight:900; letter-spacing:.1em; text-transform:uppercase; }.history header small { color:rgba(8,17,13,.5); font-size:.72rem; }.history__list { border-left:2px solid rgba(35,89,49,.16); display:flex; flex-direction:column; gap:.7rem; margin-left:.55rem; padding-left:1rem; }.history article { display:flex; gap:.65rem; position:relative; }.history__icon { align-items:center; background:#235931; border:3px solid #f4f4f0; border-radius:50%; color:#fff; display:flex; height:30px; justify-content:center; left:-1.95rem; position:absolute; top:0; width:30px; }.history article.note .history__icon { background:#a35b10; }.history article.payment .history__icon { background:#1b4d7e; }.history article > div { display:flex; flex-direction:column; gap:.14rem; }.history strong { font-size:.8rem; }.history p { color:rgba(8,17,13,.68); font-size:.76rem; line-height:1.4; }.history article small { color:rgba(8,17,13,.45); font-size:.68rem; }.history__empty { align-items:center; background:rgba(35,89,49,.05); border:1px dashed rgba(35,89,49,.22); border-radius:13px; color:rgba(8,17,13,.55); display:flex; flex-direction:column; font-size:.78rem; gap:.4rem; padding:1rem; text-align:center; }.history__empty i { color:#235931; font-size:1.2rem; }
</style>
